USE intro_sql;

SHOW TABLES;

CREATE TABLE EMPLOYEES(
    EMP_ID INT NOT NULL,
    EMP_NAME VARCHAR(50),
    MANAGER_NAME VARCHAR(100),
    DIVISION INT,
    PRIMARY KEY (EMP_ID)
);

SELECT * FROM employees;

-- ALTER TABLE employees ADD GENDER VARCHAR(1);
-- ALTER TABLE employees DROP COLUMN GENDER ;
-- INSERT INTO  EMPLOYEES VALUES(01, "Sameen Zaki", "Babloo Manager", 91);
-- INSERT INTO  EMPLOYEES VALUES(2, "Zoraiz Arsalan", "Zeemal Arsalan", 92);

SELECT EMP_ID, EMP_NAME FROM employees;

SELECT COUNT(*) FROM EMPLOYEES;

SELECT COUNT(EMP_ID) AS RECORD_COUNT FROM EMPLOYEES;

SELECT * FROM EMPLOYEES WHERE EMP_NAME = 'Sameen Zaki';

SELECT * FROM EMPLOYEES WHERE EMP_NAME = 'Sameen Zaki' and EMP_ID = 1;

SELECT * FROM EMPLOYEES WHERE EMP_NAME LIKE '%N';

SELECT * FROM EMPLOYEES WHERE EMP_NAME LIKE 'S%';

SELECT * FROM EMPLOYEES WHERE EMP_ID IN (1,2);

SELECT * FROM EMPLOYEES WHERE EMP_NAME LIKE '%N%';

SELECT * FROM EMPLOYEES WHERE EMP_NAME LIKE 'SA%';

UPDATE EMPLOYEES SET EMP_ID = '3' WHERE EMP_NAME = 'Sameen Zaki';

UPDATE EMPLOYEES SET EMP_ID = '3', MANAGER_NAME = "Tabloo Manager" WHERE EMP_NAME = 'Sameen Zaki';

UPDATE employees SET emp_id = emp_id + 2 where emp_id = 2;
